[project]
name = "kge-kubectl-get-events"
version = "0.8.8"
description = "Kubernetes utility for viewing pod and failed replicaset events"
authors = [ {name = "Jesse Goodier", email = "31039225+jessegoodier@users.noreply.github.com"} ]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.13,<4.0"
dependencies = [
    "rich (>=13.7.0,<14.0.0)",
    "kubernetes (>=32.0.1,<33.0.0)"
]

keywords = ["kubernetes", "troubleshooting", "kubectl", "events", "pod", "replicaset", "failed", "replicaset", "event"]

[project.urls]
Homepage = "https://github.com/jessegoodier/kge"
Repository = "https://github.com/jessegoodier/kge"
Documentation = "https://github.com/jessegoodier/kge/blob/main/README.md"
"Bug Tracker" = "https://github.com/jessegoodier/kge/issues"

[project.scripts]
kge = "kge.cli.main:main"

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
requires-poetry = ">=2.0"
include = [
    "src/kge/completion/_kge"
]
packages = [{include = "kge", from = "src"}]

[tool.poetry.group.test.dependencies]
coverage = ">=7.2.0"
pytest = ">=8.0"
pytest-cov = ">=4.0"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
python_classes = ["Test*"]