[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.package-data]
aimat = ["docker/docker-compose.yml"]

[project]
name = "aimat"
version = "0.1.4"
description = "AIMAT: AI Music Artist Toolkit - Simplified AI Music workflows."
authors = [{ name = "Eric Browne" }]
license = { text = "MIT" }
dependencies = ["python-osc", "docker", "psutil"]
readme = { file = "README.md", content-type = "text/markdown" }

[project.scripts]
aimat = "aimat.cli:main"
