[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "doomarena-browsergym"
version = "0.0.2"
description = "BrowserGym extensions for DoomArena"
authors = [
  { name="Leo Boisvert", email="leo.boisvert@servicenow.com" },
  { name="Abhay Puri", email="abhay.puri@servicenow.com" },
  { name="Gabriel Huang", email="gabriel.huang@servicenow.com" },
  { name="Mihir Bansal", email="mihir.bansal@servicenow.com" },
  { name="Chandra Kiran Reddy Evuru", email="chandrakiranreddy.evuru@servicenow.com" },
  { name="Avinandan Bose", email="avibose@uw.edu" },
  { name="Maryam Fazel", email="mfazel@uw.edu" },
  { name="Quentin Cappart", email="quentin.cappart@polymtl.ca" },
  { name="Alexandre Lacoste", email="alexandre.lacoste@servicenow.com" },
  { name="Alexandre Drouin", email="alexandre.drouin@servicenow.com" },
  { name="Krishnamurthy DJ Dvijotham", email="dj.dvijotham@servicenow.com" },
]
maintainers = [
  { name="Gabriel Huang", email="gabriel.huang@servicenow.com" },
  { name="Leo Boisvert", email="leo.boisvert@servicenow.com" },
]
readme = "README.md"
requires-python = ">=3.10"
license = { text = "Apache-2.0" }

dependencies = [
    "doomarena>=0.0.2",
    "playwright",
    "browsergym",
    "agentlab"
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true  # important for sharing the doomarena.* namespace