[project]
name = "heliodash"
version = "0.0.15"
description = "Heliosphere Dashboard (HelioDash) is an open-source tool for visualizing heliosphere-related data."
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Mingyu Jeon"}]
dependencies = [
    "astropy[all]>=6.1.7",
    "beautifulsoup4>=4.13.3",
    "ffmpeg-python>=0.2.0",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "ply>=3.11",
    "streamlit>=1.44.1",
    "sunpy[all]>=6.0.5",
]

[project.urls]
Homepage = "https://github.com/mgjeon/heliodash"
Repository = "https://github.com/mgjeon/heliodash"
Issues = "https://github.com/mgjeon/heliodash/issues"

[project.optional-dependencies]
dev = ["ruff"]

[build-system]
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["heliodash"]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
extend-select = ["I"]

[dependency-groups]
dev = [
    "ruff>=0.11.5",
]
