[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyspat"
version = "0.1.3"
description = "Spatial point pattern analysis in Python, inspired by spatstat"
authors = [
    { name = "Jack Peyton", email = "jpeyton01@qub.ac.uk" }
]
readme = "README.md"
license = { file = "LICENCE" }
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "pandas",
    "plotly"
]
