[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "deebeebros"
version = "0.0.004"
authors = [
  { name="Victor G.B. Peters", email="victor@jeex.eu" },
]
dependencies = [
    "PyYAML",
    "pytz",
    "certifi",
    "requests",
    "pyperclip",
    "colorama",
    "platformdirs"
]
description = "DeeBeeBros.com makes you dig coding"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages]
find = {}

[project.scripts]
cli-name = "deebeebros.__init__:run"

[project.urls]
Homepage = "https://github.com/jeex/deebeebros"
Issues = "https://github.com/jeex/deebeebros/issues"


