[project]
name = "loop-to-recursion"
version = "0.1.0"
description = "Convert the given Python code into an equivalent code without for/while loops"
authors = [
    {name = "Yuki Kobayashi",email = "drsuaimqjgar@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
packages = [{include = "loop_to_recursion", from = "src"}]

[tool.poetry.scripts]
loop-to-recursion= "loop_to_recursion.loop_to_recursion:cli"


[tool.poetry.group.dev.dependencies]
ruff = "^0.11.2"
mypy = "^1.15.0"
pytest = "^8.3.5"
yamllint = "^1.37.0"

[tool.ruff]
line-length = 127

[tool.mypy]
strict = true

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
