[project]
name = "feedmob-mcp-adjust"
version = "1.0.0"
description = "Feedmob MCP Server of Adjust - MMP MCP Server"
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = [
 "httpx[socks]>=0.27.2",
 "mcp>=1.3.0",
]

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
feedmob-mcp-adjust = "feedmob_mcp_adjust:main"
