[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "diffusionlab"
version = "3.0.2"
description = "Easy no-frills implementations of common abstractions for diffusion models."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax>=0.6.0",
]

[project.optional-dependencies]
docs = [
    "furo>=2024.8.6",
    "myst-parser>=4.0.1",
    "sphinx>=8.2.3",
]
dev = [
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
    "ruff>=0.11.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/diffusionlab"]

[tool.ruff.lint]
ignore = [
    "E731",  # This is the rule which prevents use of lambda expressions
]
