[tool.poetry]
name = "ros-launch-analyzer"
version = "0.1.1"
description = ""
authors = ["Daisuke Sato <tiryoh@gmail.com>"]
readme = "README.md"
repository = "https://github.com/Tiryoh/ros-launch-analyzer"

[tool.poetry.dependencies]
python = "^3.8.1"
graphviz = "^0.20.3"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.2"
flake8-isort = "^6.1.1"
flake8-unused-arguments = "^0.0.13"
mypy = "^1.14.1"
pytest = "^8.3.4"
pytest-github-actions-annotate-failures = ">=0.2,<0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ros-launch-analyzer = "ros_launch_analyzer.cli:main"
