[tool.poetry]
name = "kge-kubectl-get-events"
version = "0.7.0"
description = "Kubernetes utility for viewing pod and failed replicaset events"
authors = ["Jesse Goodier <31039225+jessegoodier@users.noreply.github.com>"]
readme = "README.md"
license = "MIT"
packages = [{include = "kge", from = "src"}]
include = [
    "src/kge/completion/_kge"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[tool.poetry.dependencies]
python = ">=3.11"
colorama = ">=0.4.6,<0.5.0"
kubernetes = ">=32.0.1,<33.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[tool.poetry.scripts]
kge = "kge.cli.main:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"