[project]
name = "dirmap-next"
version = "25.4.20"
description = "https://github.com/H4ckForJob/dirmap; thank h4ckforfun"
readme = "README.md"
authors = [
    { name = "LIghtJUNction", email = "LIghtJUNction.me@gmail.com" },
    { name = "h4ckforfun", email = "xxlin.ujs@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "gevent>=25.4.1",
    "lxml>=5.3.2",
    "progressbar2>=4.5.0",
    "requests>=2.32.3",
]

[project.scripts]
dirmap = "dirmap.dirmap:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
