[project]
name = "resopath"
version = "0.1.0"
description = "Reliable path resolution for Python apps, even in frozen environments like PyInstaller."
authors = [{name = "Lounes ALLIOUI", email = "la.lounas.allioui.pro@gmail.com"}]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.7"
dependencies = []

[project.scripts]
resopath = "resopath.cli:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pytest>=7.4.4",
]
