[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "workflow-graph"
version = "0.3.0"
authors = [
    { name="Dexter Awoyemi", email="dexter@dextersjab.xyz" },
]
description = "A lightweight package for managing workflow graphs"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["workflow_graph"]

[tool.pytest.ini_options]
pythonpath = [
  "src"
] 