[project]
name = "discord-mcp-server"
version = "0.1.3"
description = "A Discord webhook server using MCP"
authors = [
    {name = "mabingyin", email = "ma786074771@outlook.com"}
]
dependencies = [
    "fastapi>=0.68.0",
    "uvicorn>=0.15.0",
    "pydantic>=2.0.0",
    "requests>=2.31.0",
    "mcp[cli]>=1.6.0",
    "pip>=25.0.1",
    "build>=1.2.2.post1",
    "twine>=6.1.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[project.scripts]
discord-mcp-server = "src.discord_mcp_server:main"
