[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "check11"
version = "2025.0.001"
authors = [
  { name="Victor G.B. Peters", email="victor@jeex.eu" },
]
dependencies = [
    "PyYAML",
    "pytz",
    "certifi",
    "requests",
    "pyperclip",
    "colorama",
    "platformdirs"
]
description = "Check11 by DeeBeeBros.com makes you dig coding"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
check11 = "check11:run"

[project.urls]
Homepage = "https://deebeebros.com"
Issues = "https://deebeebros.com/contact"

