[tool.poetry]
name = "asyncpg-connector"
version = "0.1.2"
description = ""
authors = ["TY <tyyyy66@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
asyncpg = "^0.30.0"
pydantic = "^2.11.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
