[project]
name = "vocably2anki"
version = "0.1.3"
description = "Converts an exported vocably deck to a simpler format suitable for Anki import"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arguably>=1.3.0",
]

[project.scripts]
vocably2anki = "v2a:main"
