[project]
name = "mcp-latest-document"
version = "0.1.0"
description = "Get the latest documents"
readme = "README.md"
keywords = ["document", "mcp", "llm"]
authors = [
    { name = "kaz56-t", email = "kaz.j11@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "build>=1.2.2.post1",
    "httpx>=0.28.1",
    "lxml>=5.4.0",
    "markdownify>=1.1.0",
    "mcp[cli]>=1.6.0",
    "python-dotenv>=1.1.0",
    "twine>=6.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.6",
]

[project.scripts]
mcp-latest-document = "mcp_latest_document:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.ruff]
line-length = 120
target-version = "py310"
