[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "morelists"
version = "0.1.8"
description = "A small and easy list you can add together like a math equation and has a expiration date for items. Mostly useful for games with stats from multiple sources. More lists will come soon."
authors = [{name = "Emanuel OdÃ©n Hesselroth", email = "emanuelodenhesselroth@gmail.com"}]
license = {text = "MIT"}
dependencies = []
requires-python = ">=3.6"  # This must be correctly set
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]