[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "npcsimulator"
version = "1.0.9"
authors = [
    {name="Jack Peyton", email="jpeyton01@qub.ac.uk"}
]
description="Python based simulator for generating MINFLUX-like Nuclear Pore Complex data."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/j-peyton/NPCPackage"
Issues = "https://github.com/j-peyton/NPCPackage/issues"