[tool.poetry]
name = "apiconfig"
version = "0.2.1.dev9"
description = "api config library"
authors = ["Leikaab <nordavindltd@gmail.com>"]
license = "Proprietary"
readme = "README.md"
homepage = "https://github.com/Leikaab/apiconfig"
repository = "https://github.com/Leikaab/apiconfig"
documentation = "https://github.com/Leikaab/apiconfig#readme"
keywords = ["api", "config", "apiauth"]
classifiers = [
    "License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]



[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-cov = "*"
pytest-xdist = "^3.5.0"
isort = "^6.0.1"
requests-mock = "^1.12.1"
autopep8 = "*"
black = "*"
yapf = "*"
bandit = "*"
flake8 = "*"
flake8-docstrings = "*"
mypy = "*"
pycodestyle = "*"
pydocstyle = "*"
pylint = "*"
pydantic = "*"
pre-commit = "*"
types-requests = "*"
ipython = "*"
ipykernel = "*"
autoflake = "^2.3.1"
types-PyYAML = "*"
python-dotenv = "^1.1.0"
bravado-core = "^6.1.1"
httpx = "^0.28.1"
pytest_httpserver = "*"
tox = "*"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 150
skip-string-normalization = false

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/Leikaab/apiconfig/issues"

