[project]
name = "orkestr-core"
version = "0.1.9"
description = "Framework for orchestrating infrastructure and services in a multi-cloud environment"
authors = [
    {name = "joel.gee.roy", email = "joel.gee.roy@murf.ai"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.10.6,<3.0.0",
    "httpx>=0.28.1,<0.29.0",
    "python-dotenv>=1.1.0,<2.0.0",
]
license = "MIT"
license-files = ["LICENSE"]

[tool.poetry]
packages = [{include = "orkestr_core", from = "src"}]

[tool.poetry.group.test.dependencies]
pytest = "^8.3.5"

[tool.poetry.group.aws]
optional = true

[tool.poetry.group.aws.dependencies]
boto3 = "^1.37.15"

[tool.pytest.ini_options]
testpaths = [ "tests" ]
pythonpath = ["src"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
