[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bool_quetion"
version = "0.1.1"
description = "Módulo para preguntar por sí o por no"
readme = "README.md"
authors = [{ name="Pablo Alejandro Carravetti", email="gpablinux@gmail.com" }]
license = {text = "MIT"}
dependencies = []

[project.urls]
"Homepage" = "https://github.com/pablinet/bool_quetion"
