[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "neurony"
version = "0.0.1"
authors = [
 { name="Ivan Vasilev", email="vasilevib@yandex.ru" },
]
description = ""
readme = "README.md"
requires-python = ">=3.10.0"
classifiers = [
   "Programming Language :: Python :: 3",
   "License :: OSI Approved :: MIT License",
   "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/dogman0121/neurony"
Issues = "https://github.com/dogman0121/neurony/issues"