[project]
name = "eureka-mcp"
version = "0.1.17"
description = "Eureka MCP - search Spring Cloud Eureka servers for debugging"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [
    {name = "czyhandsome", email = "czyhandsome@foxmail.com"},
]
keywords = ["protocol", "mcp", "server", "eureka", "spring-cloud"]
dependencies = [
    "requests>=2.32.3",
    "mcp-python>=0.1.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mcpeureka"]

[project.scripts]
eureka-mcp = "mcpeureka.main:main"
