[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mimir-mcp"
version = "0.1.6"
description = "MCP server for Mimir AI"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Justin Garofolo", email = "justin@trymimir.ai"}
]
dependencies = [
    "httpx",
    "pydantic",
    "mcp",
    "fastmcp>=2.2.0",
    "mimir-api>=0.1.2"
]

[project.urls]
"Homepage" = "https://github.com/trymimirai/mimir-mcp"
"Bug Tracker" = "https://github.com/trymimirai/mimir-mcp/issues"
"License" = "https://github.com/trymimirai/mimir-api/blob/main/LICENSE"

[project.optional-dependencies]
dev = [
    "pytest",
    "black"
]

[project.scripts]
mimir-mcp = "mimir_mcp.main:main"

[tool.setuptools.packages.find]
include = ["mimir_mcp*"]