[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "serato-tools"
version = "1.12.0"
description = "Serato library and track metadata modification"
readme = "README.md"
authors = [
    { name = "bvandercar-vt", email = "bvandercar@outlook.com" }
]
license = { file = "LICENSE" }
dependencies = [
    "mutagen"
]

[project.optional-dependencies]
waveform_drawing = [
    "pillow"
]
beatgrid_analysis = [
    "librosa",
    "numpy"
]

[tool.setuptools]
packages = [
    "serato_tools",
    "serato_tools.utils",
]

[tool.setuptools.package-dir]
serato_tools = "src"

[project.scripts]
analyze_beatgrid = "track_beatgrid:main"