[project]
name = "leaflock"
version = "0.3.0"
authors = [
  { name="David Wiley", email="david.wiley@gmail.com" },
  { name="Joshua Maddy", email="joshuadcmaddy@gmail.com" },
]
description = "OELMs generative textbook definition."
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "AGPL-3.0-or-later"

dependencies = [
    "alembic>=1.15.1",
    "bidict>=0.23.1",
    "dotenv>=0.9.9",
    "pydantic>=2.10.6",
    "sqlalchemy>=2.0.39",
]

[project.urls]
Homepage = "https://github.com/kalendar/leaflock"
Issues = "https://github.com/kalendar/leaflock/issues"

[dependency-groups]
dev = [
    "build>=1.2.2.post1",
    "hatchling>=1.27.0",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "twine>=6.1.0",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/leaflock"]
